### ISSUE TITLE
Internal Server Error:   Spawner failed to start

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud-docker-jupyterhub#17]
@isuftin , I tried to login to our CHS JupyterHub today, found it not running.   

Tried to start it, got this:

![2017-10-17_10-23-09](https://user-images.githubusercontent.com/1872600/31670363-682b48bc-b325-11e7-9848-fbe38ddb6e6b.png)

**Comment by isuftin** [comment]
I'll check it out

**Comment by isuftin** [comment]
Seeing this in the logs...

```
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | [W 2017-10-17 14:57:35.107 isuftin configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | [I 2017-10-17 14:57:41.727 isuftin manager:40] [nb_conda_kernels] enabled, 3 kernels found
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | /opt/conda/lib/python3.6/site-packages/traitlets/config/configurable.py:84: UserWarning: Config option `cookie_name` not recognized by `HubOAuth`.
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   self.config = config
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | Traceback (most recent call last):
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     value = obj._trait_values[self.name]
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | KeyError: 'oauth_client_id'
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | During handling of the above exception, another exception occurred:
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | Traceback (most recent call last):
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     main()
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     return SingleUserNotebookApp.launch_instance(argv)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     app.initialize(argv)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "<decorator-gen-7>", line 2, in initialize
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     return method(app, *args, **kwargs)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1364, in initialize
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     self.init_webapp()
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 393, in init_webapp
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     self.init_hub_auth()
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 388, in init_hub_auth
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     if not self.hub_auth.oauth_client_id:
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     return self.get(obj, cls)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     value = self._validate(obj, dynamic_default())
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 593, in _validate
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     value = self._cross_validate(obj, value)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 599, in _cross_validate
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     value = obj._trait_validators[self.name](obj, proposal)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 907, in __call__
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     return self.func(*args, **kwargs)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |   File "/opt/conda/lib/python3.6/site-packages/jupyterhub/services/auth.py", line 439, in _ensure_not_empty
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    |     raise ValueError("%s cannot be empty." % proposal.trait.name)
jupyter-90613d4f8204b906ead85556f075fd71-1.1.ea2e7uwdmzpc@IGSCHSi-0dd10d.usgs.chs.ead    | ValueError: oauth_client_id cannot be empty.
```

That's an interesting one. Inspecting further...

**Comment by isuftin** [comment]
This seems to be a breaking issue with JupyterHub 0.8.0 which got deployed around October 13th

https://github.com/jupyterhub/wrapspawner/issues/11

I am reverting back to JupyterHub 0.7.2 now. I will notify you when it's back up!

**Comment by isuftin** [comment]
@rsignell-usgs Should be fixed. 

Launched JupyterHub 0.8.0. Launched the latest single-user notebook launcher. 

Had to remove the previous JupyterHub docker volumes since the new JupyterHub did not automatically update the underlying sqlite database.

All should be working at this point.
